import { ThemeProvider } from "@mui/material/styles";
import theme from "./theme";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Project Planner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <ThemeProvider theme={theme}>
          {children}
          <ToastContainer />
        </ThemeProvider>
      </body>
    </html>
  );
}

